/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"

#include "core_cm3.h"
#include "lcd.h"
#include "MYRTOS_FIFO.h"
#include "Scheduler.h"


Task_ref Task1,Task2,Task3,Task4;
unsigned char  Task1LED ,Task2LED,Task3LED,Task4LED;


void task1()
{
	while(1){
		//Task 4 Code
		Task1LED ^=1;
		MYRTOS_TaskWait(500,&Task1);
	}
}
void task2()
{
	while(1){
		//Task 4 Code
		Task2LED ^=1;
		MYRTOS_TaskWait(1000,&Task2);
	}
}
void task3()
{
	while(1){
		//Task 4 Code
		Task3LED ^=1;
		MYRTOS_TaskWait(2000,&Task3);
	}
}

void task4()
{
	while(1){
		//Task 4 Code
		Task4LED ^=1;
		MYRTOS_TaskWait(4000,&Task4);
	}

}
int main(void)
{
	MYRTOS_errorID error ;
	//HW_Init(Initialize CLockTree, RestController)
	HW_init();

	if(MYRTOS_init()!= NoError)
		while(1);



	Task1.Stack_Size=1000;
	Task1.p_TaskEntry=task1;
	Task1.priority=4;
	strcpy(Task1.TaskName ,"task_1");


	Task2.Stack_Size=1000;
	Task2.p_TaskEntry=task2;
	Task2.priority=3;
	strcpy(Task2.TaskName ,"task_2");



	Task3.Stack_Size=1000;
	Task3.p_TaskEntry=task3;
	Task3.priority=2;
	strcpy(Task3.TaskName ,"task_3");



	Task4.Stack_Size=1000;
	Task4.p_TaskEntry=task4;
	Task4.priority=1;
	strcpy(Task4.TaskName ,"task_4");

	error+=MYRTOS_CreateTask(&Task1);
	error+=MYRTOS_CreateTask(&Task2);
	error+=MYRTOS_CreateTask(&Task3);
	error+=MYRTOS_CreateTask(&Task4);


	MYRTOS_ActivateTask(&Task1);
	MYRTOS_ActivateTask(&Task2);
	MYRTOS_ActivateTask(&Task3);
	MYRTOS_ActivateTask(&Task4);



	MYRTOS_STARTOS();

	while (1)
	{

	}
}







