/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"

#include "core_cm3.h"
#include "lcd.h"
#include "MYRTOS_FIFO.h"
#include "Scheduler.h"



int main(void)
{
	MYRTOS_errorID error ;
	//HW_Init(Initialize CLockTree, RestController)
	HW_init();

	if(MYRTOS_init()!= NoError)
		while(1);




	MYRTOS_STARTOS();

	while (1)
	{

	}
}







