/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef unsigned int uint32_t;

//GPIO address
#define GPIOA_BASE	0x40010800
#define GPIOA_CRL	*(volatile uint32_t *)(GPIOA_BASE+0x00)
#define GPIOA_CRH	*(volatile uint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_ODR	*(volatile uint32_t *)(GPIOA_BASE+0x0C)


//RCC Registers
#define RCC_BASE	0x40021000
#define RCC_APB2ENR	*(volatile uint32_t *)(RCC_BASE+0x18)//APB2 peripheral clock enable register
#define RCC_CR		*(volatile uint32_t *)(RCC_BASE+0x00)//Clock control register
#define RCC_CFGR	*(volatile uint32_t *)(RCC_BASE+0x04)//Clock configuration register
//Bit Configuration
#define IOPAEN 	(1UL<<2)
#define AFIOEN	(1UL<<0)
#define HSION	(1UL<<0)


//EXTI
#define EXTI_BASE	0x40010400
#define EXTI_IMR	*(volatile uint32_t *)(EXTI_BASE+0x00)//Interrupt mask register
#define EXTI_RTSR	*(volatile uint32_t *)(EXTI_BASE+0x08)//Rising trigger selection register
#define EXTI_FTSR	*(volatile uint32_t *)(EXTI_BASE+0x0C)//Falling trigger selection register
#define EXTI_PR		*(volatile uint32_t *)(EXTI_BASE+0x14)//Pending register

//AFIO
#define AFIO_BASE	0x4001 0000	//alternate-function I/O
#define AFIO_EXTICR1	*(volatile uint32_t *)(EXTI_BASE+0x08)//External interrupt configuration register 1


//NVIC /*Nested vectored interrupt controller*/
#define NVIC_BASE	0xE0000000
#define NVIC_EXTIE0		*(volatile uint32_t *)(NVIC_BASE+0xE100)



void GPIO_init(void)
{
	//pin 13  in PORTA is OUTPUT
	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;

	//PIN0 in PORTA is Floating input (reset State)
	GPIOA_CRL |=(1<<2);
}

void RCC_init(void)
{
	//	Bit 0 HSION: Internal high-speed clock enable
	RCC_CR 		|=HSION;
	//IO port A clock enable
	RCC_APB2ENR |=IOPAEN;
	//Alternate function IO clock enable
	RCC_APB2ENR |=AFIOEN;

}

void EXTI_init(void)
{
	//EXTI0 Configuration for PORTA0
	AFIO_EXTICR1=0;

	//1: Interrupt request from Line x is not masked
	EXTI_IMR  |=(1<<0);
	//1: Rising trigger enabled (for Event and Interrupt) for input line.
	EXTI_RTSR |=(1<<0);

	//Enable NVIC Ireq6 --> EXTI0
	NVIC_EXTIE0|=(1<<6);

}

int main(void)
{
	RCC_init();
	GPIO_init();
	EXTI_init();
    while(1);
}

void EXTI0_IRQHandler(void)
{

	//ISR Happen when Rising Edge Happen in PORTA pin 0
	//Toggle Bit in PORTA pin 13
	GPIOA_ODR ^=(1<<13);
	//This bit is set when the selected edge event arrives on the external interrupt line.
	//This bit is cleared by writing a ‘1’ into the bit.
	EXTI_PR |=(1<<0);
}
