/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"

#include "core_cm3.h"
#include "lcd.h"

#include "Scheduler.h"


Task_ref Task1,Task2,Task3;

void task1()
{
	while(1){
		//Task 1 Code
	}
}
void task2()
{
	while(1){
		//Task 2 Code
	}
}
void task3()
{
	while(1){
		//Task 2 Code
	}
}

int main(void)
{
	MYRTOS_errorID error ;
	//HW_Init(Initialize CLockTree, RestController)
	HW_init();

	if(MYRTOS_init()!= NoError)
		while(1);


	Task1.Stack_Size=1024;
	Task1.p_TaskEntry=task1;
	Task1.priority=3;
	strcpy(Task1.TaskName ,"task_1");


	Task2.Stack_Size=1024;
	Task2.p_TaskEntry=task2;
	Task2.priority=3;
	strcpy(Task2.TaskName ,"task_2");



	Task3.Stack_Size=1024;
	Task3.p_TaskEntry=task3;
	Task3.priority=3;
	strcpy(Task3.TaskName ,"task_3");

	error+=MYRTOS_CreateTask(&Task1);
	error+=MYRTOS_CreateTask(&Task2);
	error+=MYRTOS_CreateTask(&Task3);


	while (1)
	{

	}
}







